# NEXT_PUBLIC_BASE_URL_API=https://u0lj6spjl3.execute-api.ap-southeast-1.amazonaws.com/Dev/api

### Register 
POST https://u0lj6spjl3.execute-api.ap-southeast-1.amazonaws.com/Dev/api/Auth/Register HTTP/1.1
Content-Type: application/json

{
   "requestId": "aaa",
    "email": "admin5@gmail.com",
    "password" : "12345"
}